server:
  port: 8081
spring:
  application:
    name: temp-project-yui
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8&connectionTimeZone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 10
      max-active: 50
      min-idle: 5
      max-wait: 20000
      validation-query: select 'x'
      validation-query-timeout: 600000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000

logging:
  level:
    org.example.ft.mapper: debug
    org.example.ft.temp.mapper: debug
    org.springframework.jdbc.datasource: debug

mybatis:
  mapperLocations: classpath*:com/temp/yui/**/*.Mapper.xml
  configuration:
    default-enum-type-handler: com.fresh.xy.mb.core.EnumTypeHandler



